/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
)

// HTTPQueryEEData - Retrieves the ee profile data of a UE
func (p *Processor) HandleQueryEEData(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle QueryEEData")

	ueId := c.Params.ByName("ueId")
	collName := "subscriptionData.eeProfileData"

	data, problemDetails := datarepository.QueryEEDataProcedure(collName, ueId)

	if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
		return
	}
	c.JSON(http.StatusOK, data)
}
