/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
	"regexp"
)

// HTTPCreateEeGroupSubscriptions - Create individual EE subscription for a group of UEs or any UE
func (p *Processor) HandleCreateEeGroupSubscriptions(c *gin.Context) {
	var eeSubscription models.EeSubscription
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&eeSubscription, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}
	logger.DataRepoLog.Infof("Handle CreateEeGroupSubscriptions")

	// pattern: '^(extgroupid-[^@]+@[^@]+|anyUE)$' -- 3GPP 29.505 5.2.29.2
	ueGroupId := c.Params.ByName("ueGroupId")
	if match, _ := regexp.MatchString("^(extgroupid-[^@]+@[^@]+|anyUE)$", ueGroupId); !match {
		problemDetail := models.ProblemDetails{
			Title:  "Invalid parameter",
			Status: http.StatusBadRequest,
			Detail: "Invalid ueGroupId",
			Cause:  "INVALID_PARAMETER",	
		}
		logger.DataRepoLog.Errorf("Invalid ueGroupId: %s", ueGroupId)
		c.JSON(http.StatusBadRequest, problemDetail)
		return
	}
	
	locationHeader := datarepository.CreateEeGroupSubscriptionsProcedure(ueGroupId, eeSubscription)

	c.Writer.Header().Set("Location", locationHeader)

	c.JSON(http.StatusCreated, eeSubscription)
}

// HTTPQueryEeGroupSubscriptions - Retrieves the ee subscriptions of a group of UEs or any UE
func (p *Processor) HandleQueryEeGroupSubscriptions(c *gin.Context) {

	logger.DataRepoLog.Infof("Handle QueryEeGroupSubscriptions")

	// pattern: '^(extgroupid-[^@]+@[^@]+|anyUE)$' -- 3GPP 29.505 5.2.29.2
	ueGroupId := c.Params.ByName("ueGroupId")
	if match, _ := regexp.MatchString("^(extgroupid-[^@]+@[^@]+|anyUE)$", ueGroupId); !match {
		problemDetail := models.ProblemDetails{
			Title:  "Invalid parameter",
			Status: http.StatusBadRequest,
			Detail: "Invalid ueGroupId",
			Cause:  "INVALID_PARAMETER",	
		}
		logger.DataRepoLog.Errorf("Invalid ueGroupId: %s", ueGroupId)
		c.JSON(http.StatusBadRequest, problemDetail)
		return
	}
	eeSubscriptionSlice, problemDetails := datarepository.QueryEeGroupSubscriptionsProcedure(ueGroupId)

	if eeSubscriptionSlice == nil && problemDetails == nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(http.StatusNotFound, pd)
	} else if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
	} 
	c.JSON(http.StatusOK, eeSubscriptionSlice)
}
