/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"
	"reflect"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/openapi/models"
	udr_context "github.com/free5gc/udr/internal/context"
	"github.com/free5gc/udr/internal/util"
	"github.com/free5gc/util/metrics/sbi"
)

func (p *Processor) ApplicationDataInfluenceDataSubsToNotifySubscriptionIdDeleteProcedure(
	c *gin.Context, subscriptionId string,
) {
	udr_context.GetSelf().InfluenceDataSubscriptions.Delete(subscriptionId)
	c.Status(http.StatusNoContent)
}

func (p *Processor) ApplicationDataInfluenceDataSubsToNotifySubscriptionIdGetProcedure(
	c *gin.Context, subscriptionID string,
) {
	udrSelf := udr_context.GetSelf()
	if value, ok := udrSelf.InfluenceDataSubscriptions.Load(subscriptionID); ok {
		record, valid := value.(*udr_context.InfluenceDataSubscriptionRecord)
		if valid && record.Subscription != nil {
			c.JSON(http.StatusOK, record.Subscription)
			return
		}
		pd := util.ProblemDetailsNotFound("USER_NOT_FOUND")
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, pd.Cause)
		c.JSON(int(pd.Status), pd)
		return
	} else {
		pd := util.ProblemDetailsNotFound("USER_NOT_FOUND")
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, pd.Cause)
		c.JSON(int(pd.Status), pd)
	}
}

func (p *Processor) ApplicationDataInfluenceDataSubsToNotifySubscriptionIdPutProcedure(
	c *gin.Context, subscriptionId string, request *models.TrafficInfluSub,
) {
	if len(request.Dnns) == 0 &&
		len(request.Snssais) == 0 &&
		len(request.InternalGroupIds) == 0 &&
		len(request.Supis) == 0 {
		pd := &models.ProblemDetails{
			Status: http.StatusBadRequest,
			Detail: "At least one of DNNs, S-NSSAIs, Internal Group IDs or SUPIs shall be provided",
		}
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(int(pd.Status)))
		c.JSON(int(pd.Status), pd)
		return
	}

	if request.NotificationUri == "" {
		pd := models.ProblemDetails{
			Status: http.StatusBadRequest,
			Detail: "Notification URI shall be provided",
		}
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(int(pd.Status)))
		c.JSON(int(pd.Status), pd)
		return
	}

	udrSelf := udr_context.GetSelf()
	target, ok := subscriptionCallbackTargetFromContext(
		c,
		models.ServiceName_NPCF_SMPOLICYCONTROL,
		models.NrfNfManagementNfType_PCF,
	)
	if !ok {
		rejectUnresolvedCallbackTarget(c)
		return
	}
	if value, ok := udrSelf.InfluenceDataSubscriptions.Load(subscriptionId); ok {
		record, valid := value.(*udr_context.InfluenceDataSubscriptionRecord)
		if valid {
			target = record.CallbackTarget
			if record.Subscription != nil && reflect.DeepEqual(*request, *record.Subscription) {
				c.Status(http.StatusOK)
				return
			}
		}
	}
	udrSelf.InfluenceDataSubscriptions.Store(subscriptionId, &udr_context.InfluenceDataSubscriptionRecord{
		Subscription:   request,
		CallbackTarget: target,
	})
	c.JSON(http.StatusOK, request)
}
