/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson"

	"github.com/free5gc/openapi/models"
	"github.com/free5gc/udr/internal/logger"
	"github.com/free5gc/udr/internal/util"
)

func (p *Processor) PatchOperSpecDataProcedure(c *gin.Context, collName string, ueId string, patchItem []models.PatchItem) {
	filter := bson.M{"ueId": ueId}
	if err := patchDataToDBAndNotify(collName, ueId, patchItem, filter); err != nil {
		logger.DataRepoLog.Errorf("PatchOperSpecDataProcedure err: %+v", err)
		pd := util.ProblemDetailsModifyNotAllowed("")
		c.JSON(int(pd.Status), pd)
		return
	}
	c.Status(http.StatusNoContent)
}

func (p *Processor) QueryOperSpecDataProcedure(c *gin.Context,  collName string, ueId string) {
	filter := bson.M{"ueId": ueId}
	data, pd := getDataFromDB(collName, filter)
	// The key of the map is operator specific data element name and the value is the operator specific data of the UE.
	if pd != nil {
		logger.DataRepoLog.Errorf("QueryOperSpecDataProcedure err: %s", pd.Detail)
		c.JSON(int(pd.Status), pd)
		return 
	}
	c.JSON(http.StatusOK, data)
}