/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
)

// HTTPGetOdbData - Retrieve ODB Data data by SUPI or GPSI
func (p *Processor) HandleGetOdbData(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle GetOdbData")

	ueId := c.Params.ByName("ueId")
	collName := "subscriptionData.operatorDeterminedBarringData"

	data, problemDetails := datarepository.GetOdbDataProcedure(collName, ueId)
	if data == nil && problemDetails == nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(int(pd.Status), pd)
	} else if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
	}
	c.JSON(http.StatusOK, data)
}
