/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/openapi/models"
	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
)

// HTTPGetIdentityData - Retrieve identity data by SUPI or GPSI
func (p *Processor) HandleGetIdentityData(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle GetIdentityData")

	ueId := c.Params.ByName("ueId")
	collName := "subscriptionData.identityData"

	data, problemDetails := datarepository.GetIdentityDataProcedure(collName, ueId)
	if data == nil && problemDetails == nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(int(pd.Status), pd)
	} else if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
	} else if data != nil {
		res := models.IdentityData{}
		gpsi, ok := (*data)["gpsi"]
		if ok {
			res.GpsiList = append(res.GpsiList, gpsi.(string))
		}
		ueId, ok := (*data)["ueId"]
		if ok {
			res.SupiList = append(res.SupiList, ueId.(string))
		}
		c.JSON(http.StatusOK, res)
	} 

}
