/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"
	"github.com/gin-gonic/gin"
	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"

)

// HTTPGetAmfSubscriptionInfo - Retrieve AMF subscription Info
func (p *Processor) HandleGetAmfSubscriptionInfo(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle GetAmfSubscriptionInfo")

	ueId := c.Params.ByName("ueId")
	subsId := c.Params.ByName("subsId")

	data, problemDetails := datarepository.GetAmfSubscriptionInfoProcedure(subsId, ueId)
	if data == nil && problemDetails == nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(int(pd.Status), pd)
	} else if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
	}
	c.JSON(http.StatusOK, data)

	// req := httpwrapper.NewRequest(c.Request, nil)
	// req.Params["ueId"] = c.Params.ByName("ueId")
	// req.Params["subsId"] = c.Params.ByName("subsId")

	// handlerMsg := message.NewHandlerMessage(message.EventGetAmfSubscriptionInfo, req)
	// message.SendMessage(handlerMsg)

	// rsp := <-handlerMsg.ResponseChan

	// HTTPResponse := rsp.HTTPResponse

	// c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
