/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
)

// HandleGetSharedData - retrieve shared data
func (p *Processor) HandleGetSharedData(c *gin.Context) {
	sharedDataIdArray := c.QueryArray("shared-data-ids")
	logger.DataRepoLog.Infof("Handle GetSharedData")

	var sharedDataIds []string
	if len(sharedDataIdArray) != 0 {
		sharedDataIds = sharedDataIdArray
		if strings.Contains(sharedDataIds[0], ",") {
			sharedDataIds = strings.Split(sharedDataIds[0], ",")
		}
	}
	collName := "subscriptionData.sharedData"

	data, problemDetails := datarepository.GetSharedDataProcedure(collName, sharedDataIds)

	if data == nil && problemDetails == nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(int(pd.Status), pd)
	} else if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
	}
	c.JSON(http.StatusOK, data)
}
