/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
)

// HTTPCreateSdmSubscriptions - Create individual sdm subscription
func (p *Processor) HandleCreateSdmSubscriptions(c *gin.Context) {
	var sdmSubscription models.SdmSubscription

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&sdmSubscription, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	logger.DataRepoLog.Infof("Handle CreateSdmSubscriptions")

	collName := "subscriptionData.contextData.amfNon3gppAccess"
	ueId := c.Params.ByName("ueId")

	locationHeader, SdmSubscription := datarepository.CreateSdmSubscriptionsProcedure(sdmSubscription, collName, ueId)

	c.Header("Location", locationHeader)
	c.JSON(http.StatusCreated, SdmSubscription)
}

// HTTPQuerysdmsubscriptions - Retrieves the sdm subscriptions of a UE
func (p *Processor) HandleQuerysdmsubscriptions(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle Querysdmsubscriptions")

	ueId := c.Params.ByName("ueId")

	response, problemDetails := datarepository.QuerysdmsubscriptionsProcedure(ueId)

	if response == nil && problemDetails == nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(int(pd.Status), pd)
	} else if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
	}
	c.JSON(http.StatusOK, response)
}
