/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"encoding/json"
	"net/http"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson"

	"github.com/free5gc/openapi/models"
	"github.com/free5gc/udr/internal/logger"
	"github.com/free5gc/udr/internal/util"
	"github.com/free5gc/util/metrics/sbi"
	"github.com/free5gc/util/mongoapi"
)

func (p *Processor) QuerySmDataProcedure(c *gin.Context, collName string, ueId string, servingPlmnId string,
	singleNssai *models.Snssai, dnn string,
) {
	filter := bson.M{"ueId": ueId, "servingPlmnId": servingPlmnId}

	if singleNssai != nil {
		if singleNssai.Sd == "" {
			filter["singleNssai.sst"] = singleNssai.Sst
		} else {
			filter["singleNssai.sst"] = singleNssai.Sst
			filter["singleNssai.sd"] = singleNssai.Sd
		}
	}

	if dnn != "" {
		dnnKey := util.EscapeDnn(dnn)
		filter["dnnConfigurations."+dnnKey] = bson.M{"$exists": true}
	}

	resp := models.Udm_SDM_SmSubsData{}

	sessionManagementSubscriptionDatas, err := mongoapi.
		RestfulAPIGetMany(collName, filter, mongoapi.COLLATION_STRENGTH_IGNORE_CASE)
	if err != nil {
		logger.DataRepoLog.Errorf("QuerySmDataProcedure err: %+v", err)
		pd := util.ProblemDetailsUpspecified("")
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, pd.Cause)
		c.JSON(int(pd.Status), pd)
		return
	}
	for _, smData := range sessionManagementSubscriptionDatas {
		var tmpSmData models.Udm_SDM_SessionManagementSubscriptionData
		err := json.Unmarshal(util.MapToByte(smData), &tmpSmData)
		if err != nil {
			logger.DataRepoLog.Debug("SmData Unmarshal error")
			continue
		}
		resp.IndividualSmSubsData = append(resp.IndividualSmSubsData, tmpSmData)

		dnnConfigurations := tmpSmData.DnnConfigurations
		tmpDnnConfigurations := make(map[string]models.Udm_SDM_DnnConfiguration)
		for escapedDnn, dnnConf := range dnnConfigurations {
			dnn := util.UnescapeDnn(escapedDnn)
			tmpDnnConfigurations[dnn] = dnnConf
		}
		smData["DnnConfigurations"] = tmpDnnConfigurations
	}
	c.JSON(http.StatusOK, resp)
}
