/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"
	"github.com/gin-gonic/gin"

	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
)

// HTTPQuerySmfRegList - Retrieves the SMF registration list of a UE
func (p *Processor) HandleQuerySmfRegList(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle QuerySmfRegList")

	collName := "subscriptionData.contextData.smfRegistrations"
	ueId := c.Params.ByName("ueId")
	data := datarepository.QuerySmfRegListProcedure(collName, ueId)

	c.JSON(http.StatusOK, data)

}
