/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
)

// HTTPCreateSmsfContextNon3gpp - Create the SMSF context data of a UE via non-3GPP access
func (p *Processor) HandleCreateSmsfContextNon3gpp(c *gin.Context) {
	var smsfRegistration models.SmsfRegistration

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&smsfRegistration, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	logger.DataRepoLog.Infof("Handle CreateSmsfContextNon3gpp")

	collName := "subscriptionData.contextData.smsfNon3gppAccess"
	ueId := c.Params.ByName("ueId")

	datarepository.CreateSmsfContextNon3gppProcedure(smsfRegistration, collName, ueId)
	
	c.Status(http.StatusNoContent)
}

// HTTPDeleteSmsfContextNon3gpp - To remove the SMSF context data of a UE via non-3GPP access
func (p *Processor) HandleDeleteSmsfContextNon3gpp(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle DeleteSmsfContextNon3gpp")

	collName := "subscriptionData.contextData.smsfNon3gppAccess"
	ueId := c.Params.ByName("ueId")

	datarepository.DeleteSmsfContextNon3gppProcedure(collName, ueId)
	c.Status(http.StatusNoContent)
}

// HTTPQuerySmsfContextNon3gpp - Retrieves the SMSF context data of a UE using non-3gpp access
func (p *Processor) HandleQuerySmsfContextNon3gpp(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle QuerySmsfContextNon3gpp")

	ueId := c.Params.ByName("ueId")
	collName := "subscriptionData.contextData.smsfNon3gppAccess"

	data, problemDetails := datarepository.QuerySmsfContextNon3gppProcedure(collName, ueId)
	if data == nil && problemDetails != nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(int(pd.Status), pd)
		return
	} else  if problemDetails != nil {
		c.JSON(int(problemDetails.Status), problemDetails)
		return
	} 
	c.JSON(http.StatusOK, data)
	
}
