/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"fmt"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/openapi/models"
	udr_context "github.com/free5gc/udr/internal/context"
)

func (p *Processor) PostSubscriptionDataSubscriptionsProcedure(
	c *gin.Context, SubscriptionDataSubscriptions models.Udr_DR_SubscriptionDataSubscriptions,
) {
	udrSelf := udr_context.GetSelf()

	newSubscriptionID := strconv.Itoa(udrSelf.SubscriptionDataSubscriptionIDGenerator)
	target, ok := subscriptionCallbackTargetFromContext(
		c,
		models.Nrf_NFMgmt_ServiceName_NUDM_SDM,
		models.Nrf_NFMgmt_NFType_UDM,
	)
	if !ok {
		rejectUnresolvedCallbackTarget(c)
		return
	}
	udrSelf.SubscriptionDataSubscriptions[newSubscriptionID] = &udr_context.SubscriptionDataSubscriptionRecord{
		Subscription:   &SubscriptionDataSubscriptions,
		CallbackTarget: target,
	}
	udrSelf.SubscriptionDataSubscriptionIDGenerator++

	/* Contains the URI of the newly created resource, according
	   to the structure: {apiRoot}/subscription-data/subs-to-notify/{subsId} */
	locationHeader := fmt.Sprintf("%s/subscription-data/subs-to-notify/%s",
		udrSelf.GetIPv4GroupUri(udr_context.NUDR_DR), newSubscriptionID)

	c.Header("Location", locationHeader)
	c.JSON(http.StatusCreated, SubscriptionDataSubscriptions)
}
