/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package processor

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/udr/internal/logger"
	datarepository "github.com/free5gc/udr/internal/sbi/datarepository"
	"github.com/free5gc/udr/internal/util"
)

// HTTPQueryTraceData - Retrieves the trace configuration data of a UE
func (p *Processor) HandleQueryTraceData(c *gin.Context) {
	logger.DataRepoLog.Infof("Handle QueryTraceData")

	collName := "subscriptionData.provisionedData.traceData"
	ueId := c.Params.ByName("ueId")
	servingPlmnId := c.Params.ByName("servingPlmnId")

	response, problemDetails := datarepository.QueryTraceDataProcedure(collName, ueId, servingPlmnId)

	if response == nil && problemDetails != nil {
		pd := util.ProblemDetailsUpspecified("")
		c.JSON(http.StatusInternalServerError, pd)
		return
	}
	c.JSON(http.StatusOK, response)
}
