/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/udr/handler/message"
	"free5gc/src/udr/logger"

	"github.com/gin-gonic/gin"
)

// CreateSmsfContextNon3gpp - Create the SMSF context data of a UE via non-3GPP access
func CreateSmsfContextNon3gpp(c *gin.Context) {
	var smsfRegistration models.SmsfRegistration
	if err := c.ShouldBindJSON(&smsfRegistration); err != nil {
		logger.DataRepoLog.Panic(err.Error())
	}

	req := http_wrapper.NewRequest(c.Request, smsfRegistration)
	req.Params["ueId"] = c.Params.ByName("ueId")

	handlerMsg := message.NewHandlerMessage(message.EventCreateSmsfContextNon3gpp, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// DeleteSmsfContextNon3gpp - To remove the SMSF context data of a UE via non-3GPP access
func DeleteSmsfContextNon3gpp(c *gin.Context) {
	req := http_wrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")

	handlerMsg := message.NewHandlerMessage(message.EventDeleteSmsfContextNon3gpp, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// QuerySmsfContextNon3gpp - Retrieves the SMSF context data of a UE using non-3gpp access
func QuerySmsfContextNon3gpp(c *gin.Context) {
	req := http_wrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")

	handlerMsg := message.NewHandlerMessage(message.EventQuerySmsfContextNon3gpp, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
