/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/udr/handler/message"
	"free5gc/src/udr/logger"

	"github.com/gin-gonic/gin"
)

// SubscriptionDataSubscriptions - Subscription data subscriptions
func PostSubscriptionDataSubscriptions(c *gin.Context) {
	var subscriptionDataSubscriptions models.SubscriptionDataSubscriptions
	if err := c.ShouldBindJSON(&subscriptionDataSubscriptions); err != nil {
		logger.DataRepoLog.Panic(err.Error())
	}

	req := http_wrapper.NewRequest(c.Request, subscriptionDataSubscriptions)

	handlerMsg := message.NewHandlerMessage(message.EventPostSubscriptionDataSubscriptions, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
