/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"free5gc/lib/http_wrapper"
	"free5gc/src/udr/handler/message"

	"github.com/gin-gonic/gin"
)

// GetSharedData - retrieve shared data
func GetSharedData(c *gin.Context) {
	sharedDataIdArray := c.QueryArray("shared-data-ids")

	req := http_wrapper.NewRequest(c.Request, nil)
	req.Query["sharedDataIds"] = sharedDataIdArray

	handlerMsg := message.NewHandlerMessage(message.EventGetSharedData, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
