/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package datarepository

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/udr/handler/message"
	"free5gc/src/udr/logger"

	"github.com/gin-gonic/gin"
)

// CreateAuthenticationStatus - To store the Authentication Status data of a UE
func CreateAuthenticationStatus(c *gin.Context) {
	var authEvent models.AuthEvent
	if err := c.ShouldBindJSON(&authEvent); err != nil {
		logger.DataRepoLog.Panic(err.Error())
	}

	req := http_wrapper.NewRequest(c.Request, authEvent)
	req.Params["ueId"] = c.Params.ByName("ueId")

	handlerMsg := message.NewHandlerMessage(message.EventCreateAuthenticationStatus, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// QueryAuthenticationStatus - Retrieves the Authentication Status of a UE
func QueryAuthenticationStatus(c *gin.Context) {
	req := http_wrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")

	handlerMsg := message.NewHandlerMessage(message.EventQueryAuthenticationStatus, req)
	message.SendMessage(handlerMsg)

	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
